server:
  port: 9876
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/test} #"jdbc:mysql://localhost:3306/test" #172.17.0.2: MySQL IPAddress (mysql container -> Inspect -> Networks -> IPAddress)
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root} #Default value is "root"
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true